# Ghostty GTK4 chrome CSS — regenerated by drmis. Styles the non-terminal
# widgetry (context menu, command palette, tab bar, scrollbar, tooltips).
{ p }:
''
  /* Ghostty GTK chrome — regenerated by drmis */
  @define-color gh_surface ${p.PIT_SURFACE};
  @define-color gh_overlay ${p.PIT_OVERLAY};
  @define-color gh_border  ${p.WING};
  @define-color gh_text    ${p.SCORE};
  @define-color gh_dim     ${p.LYRIC};
  @define-color gh_accent  ${p.ROOT};
  @define-color gh_sep     ${p.MUTE};

  popover.menu > contents {
      background-color: @gh_surface;
      border: 1px solid @gh_border;
      border-radius: 8px;
      padding: 4px;
  }
  popover.menu modelbutton {
      border-radius: 6px;
      color: @gh_text;
      padding: 4px 10px;
  }
  popover.menu modelbutton:hover,
  popover.menu modelbutton:focus {
      background-color: alpha(@gh_accent, 0.20);
      color: @gh_text;
  }
  popover.menu modelbutton:disabled { color: @gh_dim; }
  popover.menu modelbutton accelerator,
  popover.menu arrow { color: @gh_dim; }
  popover.menu separator {
      background-color: @gh_sep;
      margin: 4px 8px;
  }

  popover > contents {
      background-color: @gh_surface;
      border: 1px solid @gh_border;
      border-radius: 8px;
      color: @gh_text;
  }
  popover > arrow {
      background-color: @gh_surface;
      border: 1px solid @gh_border;
  }

  listview row, list row {
      color: @gh_text;
      border-radius: 6px;
  }
  listview row:hover, list row:hover,
  listview row:selected, list row:selected {
      background-color: alpha(@gh_accent, 0.20);
      color: @gh_text;
  }

  entry {
      background-color: @gh_overlay;
      color: @gh_text;
      border: 1px solid @gh_border;
      border-radius: 6px;
      caret-color: @gh_accent;
  }
  entry selection {
      background-color: alpha(@gh_accent, 0.35);
      color: @gh_text;
  }

  tabbar, tabbar .box { background-color: @gh_surface; }
  tabbar tab { color: @gh_dim; }
  tabbar tab:checked {
      color: @gh_text;
      background-color: alpha(@gh_accent, 0.15);
  }

  scrollbar slider {
      background-color: alpha(@gh_text, 0.25);
      border-radius: 8px;
  }
  scrollbar slider:hover { background-color: alpha(@gh_text, 0.45); }

  tooltip {
      background-color: @gh_surface;
      border: 1px solid @gh_border;
      border-radius: 6px;
  }
  tooltip label { color: @gh_text; }
''
