{ ... }:
{
  imports = [ ../../modules/myln/module.nix ];

  myln = {
    # Disabled: CUDA llama-cpp rebuild cost isn't worth it on fixed hardware.
    # Logic/config kept intact in case it's worth reviving later.
    enable = false;
    user = "prepko";
    cudaSupport = true;
    gpuLayers   = 999;

    modelPath = "/var/lib/myln/models/phi3.5-mini-q4.gguf";
    modelUrl  = "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf";

    embeddingModelPath = "/var/lib/myln/models/nomic-embed-text-v1.5.Q4_K_M.gguf";
    embeddingModelUrl  = "https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.Q4_K_M.gguf";
    embeddingCtxSize   = 8192;
    embeddingBatchSize = 8192;

    # /etc/nixos covers the whole flake — desktop + surface configs all in one.
    # system-map.md (generated by `myln-treemap`) teaches it the general filesystem
    # layout outside the flake — rerun myln-treemap + embed after layout changes.
    docPaths = [
      "/home/prepko/nixos"
      "/var/lib/myln/system-map.md"
    ];

    treeRoots = [
      "/home/prepko"
      "/srv"
      "/var/lib"
      "/mnt"
    ];

    topK        = 5;
    maxTokens   = 256;
    ctxSize     = 4096;
    temperature = "0.2";

    diagnosisMaxErrors  = 20;
    diagnosisMaxTokens  = 1500;
    diagnoseTime        = "00:00";
    diagnoseTimeout     = 120;

    logIgnoreUnits = [
      "dbus-broker-launch"   # startup bus races, never actionable
      "bluetoothd"           # expected errors when no device paired
      "liblixmain-tests"    # lix unit tests testing their own crash handler — intentional throws
    ];

    logIgnorePatterns = [
      "^\\+"                 # stack trace continuation lines leaking through awk field parse
    ];

    diagnoseSystemContext = ''
      Hardware: i5-9600K, GTX 1660, dual DP monitors. NixOS 26.11 with niri compositor.
      Known benign/expected errors — mention briefly but do not escalate:
        - "SGX disabled or unsupported by BIOS": CPU lacks SGX, not configurable.
        - "watchdog0: watchdog did not stop!": harmless on shutdown/reboot.
        - "sshd-session: mm_reap: child terminated by signal 15": normal SSH disconnect.
        - "systemd-tty-ask-password-agent: Failed to send": no TTY agent at headless boot stages.
        - "greetd: gkr-pam: unable to locate daemon control file": greetd does not run gnome-keyring; ignore.
      Disambiguation: any retrieved Nix config containing 'temperature = "..."' refers to an LLM
      inference sampling parameter (range 0.0–1.0), NOT a hardware temperature threshold.
      The screen locker is hyprlock; core dumps from it are recurring and low-priority unless daily.
    '';
  };
}
