# Niri Theme: olive
[colors]
background = "#3b3f31"
text = "#ffffff"
cursor = "#7a7d4f"

[colors.selection]
border = "#d4ebb7"
background = "#585b43"

[colors.hints]
start = "#908c65"
end = "#9dbb77"
