# lix-logout style CSS — regenerated by drmis. No hardcoded hex.
# Small popup (a plain floating window centred by a niri window-rule, not
# full-screen). Flat swaync vocabulary: WING shell + 1px thread border +
# the house hard offset (container shell — the one place it survives).
# The four action buttons sit proud in a recessed DIM tray: uniform
# radiusLg keycaps, 1px keyline, one soft drop, :hover presses into the
# well. Per-action fills kept, painted flat (Lock=FIFTH, Logout=ROOT,
# Reboot=FORTE, Shutdown=SOTTO).
# A drmis-tinted nix mark (state/nix-mark-img) sits above the tray — the
# same mark the greeter and the lock screen carry.
# See home/niri/swaync/style.nix.
{ p, l }:
''
  * {
      background-image: none;
      text-shadow: none;
      font-family: "JetBrainsMono Nerd Font", monospace;
  }

  window {
      background-color: ${p.WING};
      border: 1px solid ${p.SCORE}8c;
      border-radius: 18px;
      box-shadow: 3px 4px 0 0 rgba(${p.STAFF}, ${p.STAFF_A_DROP});
  }

  .lix-logout-card {
      background-color: ${p.DIM};
      border-radius: 12px;
      box-shadow: inset 0 2px 4px rgba(${p.STAFF}, ${p.STAFF_A_INSET_BOT});
      padding: 18px;
  }

  button.lix-logout-btn {
      color: ${p.SHADOW};
      border: 1px solid ${p.SCORE}26;
      border-radius: 12px;
      margin: 8px;
      min-width: 110px;
      min-height: 90px;
      outline-style: none;
      text-shadow: none;
      box-shadow: 0 2px 3px rgba(${p.STAFF}, ${p.STAFF_A_DROP});
      transition: all 0.15s ease-in-out;
  }

  button.lix-logout-btn:hover {
      box-shadow: inset 0 1px 3px rgba(${p.STAFF}, ${p.STAFF_A_HOVER});
  }

  button.lix-logout-btn:focus {
      outline-style: none;
  }

  /* Per-action fills — flat, no tilt, no bespoke shape. */
  button.lix-logout-btn-lock     { background-color: ${p.FIFTH}; }
  button.lix-logout-btn-logout   { background-color: ${p.ROOT}; }
  button.lix-logout-btn-reboot   { background-color: ${p.FORTE}; }
  button.lix-logout-btn-shutdown { background-color: ${p.SOTTO}; }

  button.lix-logout-btn.armed {
      background-color: ${p.FORTE};
      border-color: ${p.SCORE}8c;
      color: ${p.HALL};
  }

  button.lix-logout-btn.armed:hover {
      box-shadow: inset 0 1px 3px rgba(${p.STAFF}, ${p.STAFF_A_HOVER});
  }

  .lix-logout-icon {
      font-size: 30px;
  }

  .lix-logout-label {
      font-size: 13px;
      font-weight: bold;
  }

  button.lix-logout-dodge {
      background-color: ${p.BAR};
      color: ${p.SCORE};
      border: 1px solid ${p.SCORE}26;
      border-radius: 9999px;
      min-width: 34px;
      min-height: 34px;
      padding: 0;
      font-size: 11px;
      outline-style: none;
      box-shadow: 0 2px 3px rgba(${p.STAFF}, ${p.STAFF_A_DROP});
      transition: left 0.08s ease-out, top 0.08s ease-out;
  }

  /* nix mark — drmis-tinted PNG (state/nix-mark-img), pre-coloured to REST,
     so no color/filter here. Shared with the greeter and the lock screen. */
  .lix-logout-mark {
      margin-bottom: 12px;
  }
''
