# Niri Theme: juniper
[colors]
background = "#1e3a4d"
text = "#ffffff"
cursor = "#47cbcc"

[colors.selection]
border = "#edf2cf"
background = "#295e70"

[colors.hints]
start = "#c8e2c5"
end = "#5aba8f"
