p: ''
/* ============================================================
 * GTK3 — system-wide flat theme (swaync vocabulary)
 * Deployed to ~/.config/gtk-3.0/gtk.css — themes every GTK3 app.
 * Nemo is the main consumer; the headerbar / menu / tooltip /
 * treeview rules also reach GTK3 dialogs elsewhere.
 * GTK3-compatible CSS (no custom properties). Regenerated by drmis.
 * Flat palette fills · one SCORE hairline · one soft STAFF drop.
 * No gradient, no text-shadow. See home/niri/swaync/style.nix.
 * ============================================================ */

/* ── Main window surface ─────────────────────────────────── */

.nemo-window {
  background-color: ${p.STAGE};
}

.nemo-window .view,
.nemo-window .icon-view,
.nemo-window .list-view {
  background-color: ${p.WING};
  color: ${p.SCORE};
}

/* ── Sidebar ─────────────────────────────────────────────── */

placessidebar {
  background-color: ${p.HALL};
  border-right: 1px solid alpha(${p.SCORE}, 0.15);
}

placessidebar > viewport > list {
  background-color: transparent;
}

/* Every sidebar row */
placessidebar > viewport > list > row {
  border-radius: 6px;
  margin: 1px 6px;
  padding: 1px 2px;
  color: ${p.REST};
  transition: background-color 0.12s ease, color 0.12s ease;
}

/* Section separator labels (Bookmarks, Devices, Network…) */
placessidebar > viewport > list > row.separator > label {
  color: ${p.BAR};
  font-size: 10px;
  font-weight: bold;
}

placessidebar > viewport > list > row:hover {
  background-color: ${p.WING};
  color: ${p.SCORE};
}

/* Selected place — ROOT wash */
placessidebar > viewport > list > row:selected,
placessidebar > viewport > list > row:selected:focus {
  background-color: rgba(${p.ROOT_RGB}, 0.28);
  color: ${p.ROOT};
}

placessidebar > viewport > list > row:selected label,
placessidebar > viewport > list > row:selected:focus label {
  color: ${p.ROOT};
}

/* ── Path bar (breadcrumbs) ──────────────────────────────── */

.path-bar > button,
.path-bar button {
  background: none;
  box-shadow: none;
  border: none;
  border-radius: 5px;
  color: ${p.REST};
  padding: 2px 7px;
  transition: background-color 0.1s ease, color 0.1s ease;
}

.path-bar > button:hover,
.path-bar button:hover {
  background-color: ${p.WING};
  color: ${p.FIFTH};
}

/* The last segment (current directory) */
.path-bar > button:last-child,
.path-bar > button:checked,
.path-bar button.text-button:active {
  color: ${p.SCORE};
  font-weight: bold;
}

/* ── File / icon view ────────────────────────────────────── */

.view:selected {
  background-color: rgba(${p.ROOT_RGB}, 0.22);
  color: ${p.SCORE};
}

.view:selected:focus {
  background-color: rgba(${p.ROOT_RGB}, 0.32);
  outline-color: ${p.ROOT};
}

/* Rubber-band selection — the band node also carries `.view`, so these
   selectors must out-specify `.nemo-window .view` (2 classes) or the opaque
   view background wins and the band paints solid. */
.nemo-window .view.rubberband,
.nemo-window .icon-view.rubberband,
.nemo-window .list-view.rubberband,
.nemo-window .view .rubberband,
.rubberband,
rubberband {
  border: 1px solid rgba(${p.ROOT_RGB}, 0.6);
  background-color: rgba(${p.ROOT_RGB}, 0.18);
}

/* ── List-view rows ──────────────────────────────────────── */

treeview.view row:selected {
  background-color: rgba(${p.ROOT_RGB}, 0.22);
  color: ${p.SCORE};
}

treeview.view row:selected:focus {
  background-color: rgba(${p.ROOT_RGB}, 0.32);
}

treeview.view row:selected > cell {
  color: ${p.FIFTH};
}

/* Column headers */
treeview.view header button {
  background: ${p.WING};
  color: ${p.REST};
  border-right: 1px solid alpha(${p.SCORE}, 0.15);
}

treeview.view header button:hover {
  background: ${p.WING};
  color: ${p.SCORE};
}

/* ── Toolbar / header bar ────────────────────────────────── */

toolbar {
  background: ${p.STAGE};
  border-bottom: 1px solid alpha(${p.SCORE}, 0.15);
}

headerbar {
  background: ${p.STAGE};
  border-bottom: 1px solid alpha(${p.SCORE}, 0.15);
  color: ${p.SCORE};
}

/* Navigation buttons (back / forward / up) */
headerbar button.image-button,
toolbar button.image-button {
  color: ${p.REST};
  border-radius: 5px;
  transition: color 0.12s ease, background-color 0.12s ease;
}

headerbar button.image-button:hover,
toolbar button.image-button:hover {
  color: ${p.SCORE};
  background-color: ${p.WING};
}

/* ── Statusbar ───────────────────────────────────────────── */

.statusbar,
statusbar {
  background-color: ${p.STAGE};
  border-top: 1px solid alpha(${p.SCORE}, 0.15);
  color: ${p.BAR};
  font-size: 11px;
  padding: 2px 8px;
}

/* ── Notebook tabs (if Nemo is opened with multiple tabs) ── */

notebook > header {
  background-color: ${p.HALL};
  border-bottom: 1px solid alpha(${p.SCORE}, 0.15);
}

notebook > header > tabs > tab {
  color: ${p.BAR};
  padding: 4px 12px;
  border-radius: 5px 5px 0 0;
}

notebook > header > tabs > tab:hover {
  color: ${p.REST};
  background-color: ${p.WING};
}

notebook > header > tabs > tab:checked {
  background-color: ${p.STAGE};
  color: ${p.ROOT};
  border-bottom: 2px solid ${p.ROOT};
}

/* ── Context menu polish ─────────────────────────────────── */

menu {
  background-color: ${p.STAGE};
  border: 1px solid alpha(${p.SCORE}, 0.15);
  border-radius: 8px;
  box-shadow: 0 2px 3px rgba(${p.STAFF}, ${p.STAFF_A_DROP});
  padding: 4px;
}

menu > menuitem {
  border-radius: 4px;
  color: ${p.SCORE};
  padding: 3px 10px;
}

menu > menuitem:hover {
  background-color: rgba(${p.ROOT_RGB}, 0.22);
  color: ${p.ROOT};
}

menu > separator {
  background-color: alpha(${p.SCORE}, 0.15);
  margin: 4px 8px;
}

/* ── Tooltips ────────────────────────────────────────────── */

tooltip {
  background-color: ${p.STAGE};
  border: 1px solid alpha(${p.SCORE}, 0.15);
  border-radius: 8px;
  padding: 4px 8px;
}

tooltip * {
  color: ${p.SCORE};
}
''
