# Swaync notification CSS — regenerated by drmis. No hardcoded hex.
{ p, l }:
let
  # ── Keycap kit ────────────────────────────────────────────────────────
  # 2005/6 iMac-keyboard language: flat matte caps, a hairline keyline, one
  # soft drop shadow, no gloss and no bevel emboss. Caps sit proud in a
  # shallow recessed tray; a pressed / :checked cap drops into it (bg goes
  # a shade darker, accent text carries the state since a black inset
  # shadow is near-invisible on a dark cap). Every tint is an alpha over
  # SCORE (light edge) or STAFF (shadow) so palette swaps need no per-theme
  # logic. The old "hem kit" emboss was cut: on a near-black ground its
  # only visible inset was a bright white top rim — that rim is what made
  # every plate read as a glossy bubble.
  keyline = "alpha(${p.SCORE}, 0.15)";
  capDrop = "0 2px 3px rgba(${p.STAFF}, ${p.STAFF_A_DROP})";
  tray    = "inset 0 2px 4px rgba(${p.STAFF}, ${p.STAFF_A_INSET_BOT})";
  capDown = "inset 0 1px 3px rgba(${p.STAFF}, ${p.STAFF_A_HOVER})";

  # Control-center shell: soft grey, mildly translucent. WING is the
  # palette's first step off the floor — a muted raised tone on every theme
  # here; 0.88 lets a hint of desktop through without the panel dissolving
  # into the (same-palette) wallpaper.
  shellBg = "alpha(${p.WING}, 0.88)";

  # SCORE keyline shared with waybar / .notification borders.
  thread = "alpha(${p.SCORE}, 0.55)";

  # Corner rounding — local, and a few px softer than the shared layout
  # scale, so the panel reads friendlier than the bar without moving niri
  # window / waybar corners with it.
  rKey   = "7";    # keycaps, framed titles, tab tops
  rCard  = "12";   # notification + slider cards, session tray
  rShell = "18";   # control-center shell

  # Faint fiber weave — control-center ground only now (it used to sit on
  # every plate: invisible on dark themes, muddy on light ones). rect fill
  # is transparent so an unsupported filter degrades to nothing.
  fiber = ''url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='90' height='90'><filter id='craft'><feTurbulence type='fractalNoise' baseFrequency='0.55' numOctaves='3' result='n'/><feColorMatrix type='matrix' values='0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.06 0' in='n' result='fiber'/><feBlend mode='multiply' in='SourceGraphic' in2='fiber'/></filter><rect width='100%25' height='100%25' filter='url(%23craft)' fill='transparent'/></svg>")'';

  # swaync loads its packaged style.css as a base at the same GTK priority as
  # this sheet, and GTK4 (≥4.22) rejects `!important` outright. The only lever
  # left is specificity: the packaged rules for the notification card and its
  # text run 3-7 selectors deep, so every override below is written at that
  # same depth and wins on load order (this sheet loads last). Prefixes:
  nRow   = ".notification-row .notification-background";
  nCard  = "${nRow} .notification";                              # the card itself (3)
  nAct   = "${nCard} .notification-default-action";              # (4)
  nBox   = "${nAct} .notification-content .text-box";            # summary/time/body (6)
  nReply = "${nAct} .notification-content .inline-reply";        # (6)
in
''
  * {
    font-family: "JetBrains Mono", monospace;
    font-size: 12px;
  }

  .notification-row { outline: none; }
  .notification-row:focus,
  .notification-row:hover { background: none; }

  /* Content card — flat STAGE cutout, hairline edge, one soft drop. Written at
     the packaged sheet's own selector depth (see prefixes in the let block)
     so it wins on load order without !important. */
  ${nCard} {
    background-color: ${p.STAGE};
    border: 1px solid ${keyline};
    border-radius: ${rCard}px;
    padding: 0;
  }
  .control-center .control-center-list .notification,
  .floating-notifications .notification {
    box-shadow: ${capDrop};
  }

  .notification-content {
    background: transparent;
    border-radius: ${rCard}px;
  }
  ${nAct} .notification-content {
    padding: 6px 10px;
  }

  .notification-content .body-image {
    border-radius: ${rKey}px;
  }

  .notification-default-action,
  .notification-action {
    padding: 4px;
    background: transparent;
    border: none;
    color: ${p.SCORE};
    border-radius: ${rKey}px;
  }
  .notification-default-action:hover,
  .notification-action:hover {
    background: ${p.WING};
    color: ${p.SCORE};
  }

  .close-button {
    background: transparent;
    color: ${p.LYRIC};
    border: none;
    border-radius: ${rKey}px;
    padding: 2px;
  }
  .close-button:hover {
    color: ${p.FORTE};
    background: ${p.WING};
  }

  ${nBox} .summary {
    font-size: 12px;
    font-weight: 700;
    color: ${p.SCORE};
    text-shadow: none;
  }
  ${nBox} .time {
    font-size: 10px;
    font-weight: 600;
    color: ${p.LYRIC};
    text-shadow: none;
    margin-right: 24px;
  }
  ${nBox} .body {
    font-size: 12px;
    font-weight: 500;
    color: ${p.LYRIC};
    text-shadow: none;
  }

  .app-icon-image {
    border-radius: ${rKey}px;
  }

  ${nRow} .notification.critical {
    background-color: rgba(${p.FORTE_RGB}, 0.18);
    border-color: alpha(${p.FORTE}, 0.6);
    box-shadow: 0 0 0 1px rgba(${p.FORTE_RGB}, 0.5), ${capDrop};
  }
  ${nRow} .notification.critical .notification-default-action .notification-content .text-box .summary {
    color: ${p.FORTE};
  }

  /* Inline reply (Claude Code & chat apps that request it), notification
     action buttons, and progress bars — matched to the keycap language, each
     selector written at the packaged sheet's depth so load order carries it. */
  ${nReply} .inline-reply-entry {
    background: ${p.DIM};
    color: ${p.SCORE};
    caret-color: ${p.ROOT};
    border: 1px solid ${keyline};
    border-radius: ${rKey}px;
    padding: 4px 8px;
  }
  ${nReply} .inline-reply-button,
  ${nCard} .notification-action > button,
  ${nCard} .notification-alt-actions button {
    background: ${p.WING};
    color: ${p.LYRIC};
    border: 1px solid ${keyline};
    border-radius: ${rKey}px;
    box-shadow: ${capDrop};
    padding: 4px 10px;
    font-weight: 700;
  }
  ${nReply} .inline-reply-button:hover,
  ${nCard} .notification-action > button:hover,
  ${nCard} .notification-alt-actions button:hover {
    background: ${p.STAGE};
    color: ${p.SCORE};
  }
  ${nReply} .inline-reply-button:disabled {
    background: ${p.DIM};
    color: ${p.REST};
    box-shadow: none;
  }
  .notification-content progressbar,
  .notification-content progressbar trough,
  .notification-content progressbar progress {
    min-height: 6px;
    border-radius: 999px;
  }
  .notification-content progressbar trough {
    background: ${p.DIM};
    border: 1px solid ${keyline};
  }
  .notification-content progressbar progress { background: ${p.ROOT}; }

  /* Empty state — the "no notifications" placeholder. */
  .control-center .control-center-list-placeholder {
    color: ${p.REST};
    font-size: 11px;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    opacity: 1;
  }

  /* ── Shell ───────────────────────────────────────────────────────────
     Soft grey, mildly translucent. Keeps the house hard-offset shadow
     (single layer, paletteized) but drops the emboss + 165deg gradient
     that turned it into a vignette. */
  .control-center {
    background-color: ${shellBg};
    background-image: ${fiber};
    background-repeat: repeat;
    border: 1px solid ${thread};
    border-radius: ${rShell}px;
    box-shadow: 3px 4px 0 0 rgba(${p.STAFF}, ${p.STAFF_A_DROP});
  }

  .control-center-list { background: transparent; }
  .notification-row .notification-background { padding: 4px 12px; }
  .control-center-list .notification { margin: 0; }

  #label-count {
    font-weight: 700;
    color: ${p.FORTE};
  }

  /* ── Section breaks ──────────────────────────────────────────────────
     Every section opens with a hairline rule + a small engraved label,
     left-set — the rule IS the break. No box frame (a frame around every
     group read as clutter). "Controls" and "Now Playing" are added as
     label# widgets in home/niri/default.nix so the four sections
     (notifications / audio / controls / media) share one rhythm. */
  .widget-title,
  .widget-label {
    background: none;
    border: none;
    border-top: 1px solid alpha(${p.SCORE}, 0.13);
    border-radius: 0;
    box-shadow: none;
    margin: 20px 12px 8px;
    padding: 12px 2px 0;
  }
  /* First section butts against the shell's inner edge — no rule above. */
  .widget-title {
    border-top: none;
    margin: 4px 12px 8px;
    padding: 2px 2px 0;
  }
  .widget-title > label,
  .widget-label > label {
    color: ${p.LYRIC};
    font-weight: 700;
    font-size: 10px;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    text-shadow: none;
  }
  .widget-title > label { font-size: 11px; }
  .widget-title > button {
    background-color: ${p.WING};
    border: 1px solid ${keyline};
    border-radius: ${rKey}px;
    box-shadow: ${capDrop};
    color: ${p.LYRIC};
    padding: 3px 10px;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    min-height: 0;
  }
  .widget-title > button:hover {
    background-color: ${p.WING};
    color: ${p.SCORE};
  }
  .widget-title > button:disabled {
    color: ${p.REST};
    box-shadow: none;
  }

  /* ── Sliders — Volume / Brightness, two flat keycap cards ──────────── */
  .widget-volume,
  .widget-backlight {
    background-color: ${p.STAGE};
    border: 1px solid ${keyline};
    border-radius: ${rCard}px;
    box-shadow: ${capDrop};
    margin: 4px 12px;
    padding: 8px 10px;
  }
  .widget-volume { margin-top: 6px; }
  .widget-backlight { margin-bottom: 10px; }

  .widget-volume label,
  .widget-backlight label {
    color: ${p.SCORE};
    font-weight: 600;
  }

  /* Slider track + knob — palette-themed (GTK ships a bright blue here).
     Recessed DIM trough (same well as the session tray), ROOT accent fill,
     a proud SCORE knob on the keycap drop shadow. */
  .widget-volume scale,
  .widget-backlight scale {
    padding: 0;
    margin: 4px 0 2px;
  }
  .widget-volume scale trough,
  .widget-backlight scale trough {
    background-color: ${p.DIM};
    border: 1px solid ${keyline};
    border-radius: 999px;
    min-height: 6px;
    box-shadow: ${tray};
  }
  .widget-volume scale highlight,
  .widget-backlight scale highlight {
    background-color: ${p.ROOT};
    border-radius: 999px;
    min-height: 6px;
  }
  .widget-volume scale:disabled highlight,
  .widget-backlight scale:disabled highlight {
    background-color: ${p.LYRIC};
  }
  .widget-volume scale slider,
  .widget-backlight scale slider {
    background-color: ${p.SCORE};
    border: 1px solid ${keyline};
    border-radius: 999px;
    box-shadow: ${capDrop};
    min-width: 16px;
    min-height: 16px;
    margin: -6px;
  }

  /* ── Session-toggle row — keycaps sunk into a recessed tray ───────── */
  .widget-menubar.session {
    margin: 4px 12px 4px;
    background-color: ${p.DIM};
    border: 1px solid ${keyline};
    border-radius: ${rCard}px;
    box-shadow: ${tray};
    padding: 6px 8px;
  }
  .widget-menubar.session .menu-button-bar button {
    background-color: ${p.WING};
    border: 1px solid ${keyline};
    border-radius: ${rKey}px;
    box-shadow: ${capDrop};
    margin: 2px;
    padding: 6px;
    font-size: 16px;
    color: ${p.LYRIC};
  }
  .widget-menubar.session .menu-button-bar button:checked {
    background-color: ${p.DIM};
    box-shadow: ${capDown};
    color: ${p.ROOT};
  }

  /* ── Connectivity / System / Appearance — always-visible cards ─────
     Same keycap language as the volume/backlight card: flat plate, native
     2-per-row flowbox, :checked cap drops into the recess. */
  .widget-buttons-grid {
    background-color: ${p.STAGE};
    border: 1px solid ${keyline};
    border-radius: ${rCard}px;
    box-shadow: ${capDrop};
    margin: 4px 12px;
    padding: 8px;
  }
  .widget-buttons-grid flowboxchild > button {
    background-color: ${p.WING};
    border: 1px solid ${keyline};
    border-radius: ${rKey}px;
    box-shadow: ${capDrop};
    margin: 3px;
    padding: 6px 8px;
    font-size: 11px;
    font-weight: 700;
    color: ${p.LYRIC};
  }
  .widget-buttons-grid flowboxchild > button.toggle:checked {
    background-color: ${p.DIM};
    box-shadow: ${capDown};
    color: ${p.ROOT};
  }

  /* ── Grouped / stacked notifications ─────────────────────────────────
     swaync stacks same-app notifications behind a peeking backing card;
     flatten it and the group header chrome onto our card language. */
  .notification-group { background: none; }
  .notification-group .notification-group-headers .notification-group-header,
  .notification-group .notification-group-headers .notification-group-icon {
    color: ${p.LYRIC};
  }
  .notification-group.collapsed .notification-row .notification,
  .notification-group.collapsed:hover .notification-row:not(:only-child) .notification {
    background-color: ${p.STAGE};
  }

  /* ── Now Playing ────────────────────────────────────────────────────
     Another flat module. The packaged stylesheet blurs the album art and
     lays a black scrim over it — knock the art back to an ambient tint,
     drop the scrim, theme the text + transport with the palette. Selectors
     match the packaged depth so no !important is needed. */
  .widget-mpris { padding: 0; }
  .widget-mpris .widget-mpris-player {
    background-color: ${p.STAGE};
    border: 1px solid ${keyline};
    border-radius: ${rCard}px;
    box-shadow: ${capDrop};
    margin: 0 12px 6px;
  }
  .widget-mpris .widget-mpris-player .mpris-background {
    filter: blur(20px);
    opacity: 0.16;
  }
  .widget-mpris .widget-mpris-player .mpris-overlay {
    background-color: transparent;
    padding: 10px 12px;
  }
  .widget-mpris .widget-mpris-player .mpris-overlay .widget-mpris-album-art {
    border-radius: ${rKey}px;
    box-shadow: ${capDrop};
    -gtk-icon-size: 44px;
  }
  .widget-mpris .widget-mpris-player .mpris-overlay .widget-mpris-title {
    font-weight: 700;
    font-size: 12px;
    color: ${p.SCORE};
  }
  .widget-mpris .widget-mpris-player .mpris-overlay .widget-mpris-subtitle {
    font-size: 11px;
    color: ${p.LYRIC};
  }
  .widget-mpris .widget-mpris-player .mpris-overlay button,
  .widget-mpris > box > button {
    background: transparent;
    border: none;
    box-shadow: none;
    color: ${p.LYRIC};
    border-radius: ${rKey}px;
    min-height: 0;
    min-width: 0;
    padding: 4px;
  }
  .widget-mpris .widget-mpris-player .mpris-overlay button:hover,
  .widget-mpris > box > button:hover {
    background-color: ${p.WING};
    color: ${p.SCORE};
  }
  .widget-mpris > box > button:disabled { color: ${p.REST}; }
''
