# Zed editor theme — regenerated by drmis. Returns attrset; caller does builtins.toJSON.
{ t }:
let
  p    = t.palette;
  ap   = if t.isLight then "light" else "dark";
  a10  = col: col + "1a";
  a20  = col: col + "33";
  a30  = col: col + "4d";
  a50  = col: col + "80";
  # extended keys not present in all palettes
  hoverBg       = p.HOVER_BG       or p.WING;
  inactiveBorder = p.BAR or p.WING;
  borderAccent  = p.LEDGER  or p.ROOT;
  wbBase        = p.PIT        or p.HALL;
  wbSurface     = p.PIT_SURFACE     or p.STAGE;
  textSecondary = p.LYRIC or p.REST;
in {
  "\$schema" = "https://zed.dev/schema/themes/v0.2.0.json";
  name       = t.slug;
  author     = "drmis";
  themes     = [{
    name       = t.slug;
    appearance = ap;
    style = {
      background                      = p.HALL;
      "surface.background"            = p.STAGE;
      "elevated_surface.background"   = p.WING;
      "panel.background"              = p.STAGE;
      "tab_bar.background"            = wbSurface;
      "tab.active_background"         = p.WING;
      "tab.inactive_background"       = p.STAGE;
      "status_bar.background"         = wbBase;
      "title_bar.background"          = wbBase;
      "title_bar.inactive_background" = p.HALL;
      "toolbar.background"            = p.STAGE;
      "drop_target.background"        = a20 p.ROOT;

      border                 = inactiveBorder;
      "border.variant"       = p.WING;
      "border.focused"       = borderAccent;
      "border.selected"      = borderAccent;
      "border.transparent"   = "#00000000";
      "border.disabled"      = p.BAR;
      "panel.focused_border" = borderAccent;
      "pane.focused_border"  = borderAccent;

      text               = p.SCORE;
      "text.muted"       = p.REST;
      "text.placeholder" = p.BAR;
      "text.disabled"    = p.BAR;
      "text.accent"      = p.ROOT;
      icon               = textSecondary;
      "icon.muted"       = p.REST;
      "icon.disabled"    = p.BAR;
      "icon.placeholder" = p.BAR;
      "icon.accent"      = p.ROOT;

      "element.background"       = "#00000000";
      "element.hover"            = hoverBg;
      "element.selected"         = p.MUTE;
      "element.active"           = p.MUTE;
      "element.disabled"         = p.BAR;
      "ghost_element.background" = "#00000000";
      "ghost_element.hover"      = hoverBg;
      "ghost_element.selected"   = p.MUTE;
      "ghost_element.active"     = p.MUTE;
      "ghost_element.disabled"   = p.BAR;

      "editor.background"                          = p.HALL;
      "editor.foreground"                          = p.SCORE;
      "editor.gutter.background"                   = p.HALL;
      "editor.line_number"                         = p.BAR;
      "editor.active_line_number"                  = p.REST;
      "editor.active_line.background"              = p.MUTE;
      "editor.highlighted_line.background"         = p.MUTE;
      "editor.indent_guide"                        = p.WING;
      "editor.indent_guide_active"                 = p.BAR;
      "editor.wrap_guide"                          = p.WING;
      "editor.active_wrap_guide"                   = p.BAR;
      "editor.invisible"                           = p.BAR;
      "editor.document_highlight.read_background"  = a20 p.FIFTH;
      "editor.document_highlight.write_background" = a20 p.SOTTO;
      "search.match_background"                    = a30 p.PIANO;
      "link_text.hover"                            = p.FIFTH;

      "scrollbar.thumb.background"       = a50 p.REST;
      "scrollbar.thumb.hover_background" = p.REST;
      "scrollbar.thumb.border"           = a50 p.REST;
      "scrollbar.track.background"       = "#00000000";
      "scrollbar.track.border"           = p.WING;

      error      = p.FORTE;  "error.background"   = a10 p.FORTE;  "error.border"   = a30 p.FORTE;
      warning    = p.PIANO;  "warning.background" = a10 p.PIANO;  "warning.border" = a30 p.PIANO;
      success    = p.SEVENTH;  "success.background" = a10 p.SEVENTH;  "success.border" = a30 p.SEVENTH;
      info       = p.FIFTH;  "info.background"    = a10 p.FIFTH;  "info.border"    = a30 p.FIFTH;
      hint       = p.ROOT;  "hint.background"    = a10 p.ROOT;  "hint.border"    = a30 p.ROOT;
      predictive = p.BAR; "predictive.background" = a10 p.BAR; "predictive.border" = a30 p.BAR;

      created  = p.SEVENTH;  "created.background"  = a10 p.SEVENTH;  "created.border"  = a30 p.SEVENTH;
      modified = p.PIANO;  "modified.background" = a10 p.PIANO;  "modified.border" = a30 p.PIANO;
      deleted  = p.FORTE;  "deleted.background"  = a10 p.FORTE;  "deleted.border"  = a30 p.FORTE;
      conflict = p.SOTTO;  "conflict.background" = a10 p.SOTTO;  "conflict.border" = a30 p.SOTTO;
      renamed  = p.FIFTH;  "renamed.background"  = a10 p.FIFTH;  "renamed.border"  = a30 p.FIFTH;
      ignored  = p.BAR; "ignored.background"  = a10 p.BAR; "ignored.border"  = a30 p.BAR;
      hidden   = p.BAR; "hidden.background"   = a10 p.BAR; "hidden.border"   = a30 p.BAR;

      "terminal.background"        = p.HALL;
      "terminal.foreground"        = p.SCORE;
      "terminal.bright_foreground" = p.SCORE;
      "terminal.dim_foreground"    = p.REST;
      "terminal.ansi.black"          = p.WING;
      "terminal.ansi.red"            = p.FORTE;
      "terminal.ansi.green"          = p.SEVENTH;
      "terminal.ansi.yellow"         = p.PIANO;
      "terminal.ansi.blue"           = p.FIFTH;
      "terminal.ansi.magenta"        = p.ROOT;
      "terminal.ansi.cyan"           = p.SOTTO;
      "terminal.ansi.white"          = p.REST;
      "terminal.ansi.bright_black"   = p.BAR;
      "terminal.ansi.bright_red"     = p.FORTE;
      "terminal.ansi.bright_green"   = p.SEVENTH;
      "terminal.ansi.bright_yellow"  = p.PIANO;
      "terminal.ansi.bright_blue"    = p.FIFTH;
      "terminal.ansi.bright_magenta" = p.ROOT;
      "terminal.ansi.bright_cyan"    = p.SOTTO;
      "terminal.ansi.bright_white"   = p.SCORE;

      syntax = {
        comment            = { color = p.BAR;  font_style = "italic"; };
        "comment.doc"      = { color = p.REST; font_style = "italic"; };
        string             = { color = p.PIANO; };
        "string.escape"    = { color = p.SOTTO; };
        "string.regex"     = { color = p.FIFTH; };
        number             = { color = p.SOTTO; };
        boolean            = { color = p.FORTE; };
        keyword            = { color = p.SEVENTH; };
        "keyword.operator" = { color = p.REST; };
        operator           = { color = p.REST; };
        function           = { color = p.SOTTO; };
        "function.builtin" = { color = p.FORTE; };
        "function.method"  = { color = p.SOTTO; };
        type               = { color = p.FIFTH; };
        "type.builtin"     = { color = p.FORTE; };
        variable           = { color = p.SCORE; };
        "variable.builtin"    = { color = p.FORTE; };
        "variable.parameter"  = { color = p.ROOT; };
        "variable.member"     = { color = p.FIFTH; };
        constant              = { color = p.PIANO; };
        "constant.builtin"    = { color = p.FORTE; };
        property              = { color = p.FIFTH; };
        attribute             = { color = p.ROOT; };
        tag                   = { color = p.FORTE; };
        "tag.attribute"       = { color = p.ROOT; };
        punctuation             = { color = p.REST; };
        "punctuation.bracket"   = { color = p.REST; };
        "punctuation.delimiter" = { color = p.REST; };
        "punctuation.special"   = { color = p.FIFTH;   };
        namespace    = { color = p.SEVENTH; };
        constructor  = { color = p.SOTTO; };
        label        = { color = p.ROOT; };
        link_uri     = { color = p.FIFTH; font_style = "underline"; };
        link_text    = { color = p.ROOT; font_style = "italic"; };
        title        = { color = p.ROOT; font_weight = 700; };
        emphasis          = { font_style = "italic"; };
        "emphasis.strong" = { font_weight = 700; };
      };

      players = [
        { cursor = p.ROOT; background = a20 p.ROOT; selection = a20 p.ROOT; }
        { cursor = p.SOTTO; background = a20 p.SOTTO; selection = a20 p.SOTTO; }
        { cursor = p.SEVENTH; background = a20 p.SEVENTH; selection = a20 p.SEVENTH; }
        { cursor = p.PIANO; background = a20 p.PIANO; selection = a20 p.PIANO; }
        { cursor = p.FIFTH; background = a20 p.FIFTH; selection = a20 p.FIFTH; }
        { cursor = p.FORTE; background = a20 p.FORTE; selection = a20 p.FORTE; }
      ];

      accents = [ p.ROOT p.FIFTH p.SOTTO p.SEVENTH p.PIANO p.FORTE ];
    };
  }];
}
