p: ''
  /* Generated by drmis — do not edit by hand */
  :root {
      --hall:  ${p.HALL};
      --stage: ${p.STAGE};
      --wing:  ${p.WING};
      --lyric: ${p.LYRIC};
      --rest:  ${p.REST};
      --root:  ${p.ROOT};
      --bar:   ${p.BAR};
  }
''
