# Fastfetch info panel JSON config — regenerated by drmis. Includes ANSI colour
# helpers for section headers; imports ./scripts.nix for command module paths.
{ t, config, pkgs, ssh ? false }:
let
  ffEsc = (builtins.fromTOML "x = \"\\u001B\"").x;
  ffAnsi = color:
    let
      hex      = builtins.substring 1 6 color;
      hexDigit = c: builtins.getAttr c {
        "0"=0;"1"=1;"2"=2;"3"=3;"4"=4;"5"=5;"6"=6;"7"=7;
        "8"=8;"9"=9;"a"=10;"b"=11;"c"=12;"d"=13;"e"=14;"f"=15;
      };
      hb = s: (hexDigit (builtins.substring 0 1 s) * 16) + hexDigit (builtins.substring 1 1 s);
      r  = toString (hb (builtins.substring 0 2 hex));
      g  = toString (hb (builtins.substring 2 2 hex));
      b  = toString (hb (builtins.substring 4 2 hex));
    in "${ffEsc}[38;2;${r};${g};${b}m";
  ffReset = "${ffEsc}[0m";
  s       = import ./scripts.nix pkgs;
  p       = t.palette;
  an      = ffAnsi;
  rs      = ffReset;
  f       = import ./fleet.nix { inherit pkgs an p; lib = pkgs.lib; rs = ffReset; };
  isD     = config.myConfig.isDesktop;
  homeDir = config.home.homeDirectory;

  # ── Box-drawing rules, all padded to the same inner width so the
  #    ╔╗ / ╠╣ / ╚╝ edges line up into one clean rectangle. ────────────────
  L    = pkgs.lib;
  boxW = 40;
  bar  = n: L.concatStrings (L.genList (_: "═") n);
  # ╠══╡ <icon>  <LABEL> ╞<fill>╣ — fixed run before <fill> is
  # "══╡ "(4) + icon(1 cell) + "  "(2) + label + " ╞"(2) = 9 + len(label).
  rule = icon: label: "╠══╡ ${icon}  ${label} ╞${bar (boxW - 9 - (builtins.stringLength label))}╣";
  # Title: "╔<dl>═ prepko@<host> ═<dr>╗" centred to inner width boxW.
  titleHost = if isD then "SWphil" else "SWsurface";
  titleTxt  = "prepko@${titleHost}";
  titlePad  = boxW - 2 - (builtins.stringLength titleTxt);
  titleFmt  = "╔${bar (titlePad / 2)} {1}@{2} ${bar (titlePad - titlePad / 2)}╗";
  fleetHosts = [ "desktop" "surface" "retro" "pi" ];
  fleetBlock = [
    "break"
    { type = "custom"; format = "${an p.SOTTO}${rule "󰒍" "FLEET"}${rs}"; }
  ] ++ map (h: { type = "command"; key = "󰒋  ${h}"; text = "${f.fleet}/bin/ff-fleet ${h}"; }) fleetHosts
    ++ [ { type = "command"; key = "󰓦  sync"; text = "${f.sync}/bin/ff-sync"; } ];

  desktopBlock = [
    "break"
    { type = "custom"; format = "${an p.FIFTH}${rule "󰸉" "DESKTOP"}${rs}"; }
    { type = "wm"; key = "󰖲  WM"; }
    { type = "shell"; key = "󱆃  Shell"; }
    { type = "terminal"; key = "󰆿  Terminal"; }
    { type = "custom"; key = "󰏘  Theme"; format = "${t.slug}"; }
    { type = "icons"; key = "󰀻  Icons"; }
    { type = "cursor"; key = "󰳾  Cursor"; }
  ];

  # inside an ssh login there is no desktop to query: show where we are attached instead
  sessionBlock = [
    "break"
    { type = "custom"; format = "${an p.FIFTH}${rule "󰌘" "SESSION"}${rs}"; }
    { type = "command"; key = "󰁔  From"; text = "${f.sessionFrom}/bin/ff-session-from"; }
    { type = "command"; key = "󰀉  Others"; text = "${f.sessionOthers}/bin/ff-session-others"; }
    { type = "shell"; key = "󱆃  Shell"; }
    { type = "custom"; key = "󰏘  Theme"; format = "${t.slug}"; }
  ];
in builtins.toJSON {
  logo    = { source = "${homeDir}/.local/share/fastfetch/logo.png"; type = "kitty"; width = 22; height = 16; padding = { right = 4; top = 9; }; };
  display = { separator = "  "; key.width = 13; color.keys = p.ROOT; };
  modules = [
    { type = "title"; format = titleFmt; color = { user = p.FORTE; host = p.ROOT; }; }
    { type = "custom"; format = "${an p.SEVENTH}${rule "󰒋" "SYSTEM"}${rs}"; }
    { type = "host"; key = "󰋑  Host"; }
    { type = "cpu"; key = "󰻠  CPU"; }
    { type = "gpu"; key = "󰾲  GPU"; }
    { type = "os"; key = "󱄅  OS"; }
    { type = "kernel"; key = "󰻀  Kernel"; }
    { type = "command"; key = "󰜗  Lix"; text = "${s.lix}"; }
    { type = "uptime"; key = "󰔛  Uptime"; }
    { type = "packages"; key = "󰏖  Packages"; }
    { type = "memory"; key = "󰍛  Memory"; percent.type = 3; }
    { type = "disk"; key = "󰋊  Disk (/)"; folders = "/"; percent.type = 3; }
  ] ++ (if isD then [
    { type = "disk"; key = "󱘲  Disk (/srv)"; folders = "/srv"; percent.type = 3; }
  ] else []) ++ [
    { type = "command"; key = "󰖂  VPN"; text = "${s.vpn}"; }
    { type = "command"; key = "󱁤  Rebuild"; text = "${s.rebuild}"; }
  ] ++ fleetBlock ++ (if ssh then sessionBlock else desktopBlock) ++ [
    "break"
    { type = "custom"; format = "${an p.ROOT}╚${bar boxW}╝${rs}"; }
    { type = "custom"; format = "  ${an p.FORTE}██████${an p.SOTTO}██████${an p.PIANO}██████${an p.SEVENTH}██████${an p.FIFTH}██████${an p.ROOT}██████${rs}"; }
  ];
}
