# Hyprlock lock screen config — regenerated by drmis. Scales for desktop vs surface.
{ p, l, config, lib }:
let
  h    = col: lib.removePrefix "#" col;
  home = config.home.homeDirectory;
  sc   = if config.myConfig.isDesktop then 1 else 2;
  px   = n: toString (n * sc);

  # Vertical layout — mark → clock → date as one cluster centred on the screen,
  # matching the greeter (pkgs/greeter/greeter/app.py: a centred column, spacing
  # 14, mark 48px) in both rhythm and placement. hyprlock's origin is y-up: a
  # POSITIVE position.y raises a widget — see the input-field below (valign=bottom,
  # position.y = +205*sc, sits ABOVE the edge). All three widgets are
  # valign=center. clockMid is the live-tune knob; mark / date / band offsets
  # derive from it so one nudge moves the lot. The 96/32 fonts are literal (not
  # sc-scaled), so clockDateGap isn't either — a scaled gap collapses onto the
  # 96px glyph at sc=1.
  clockFont    = 96;
  dateFont     = 32;
  clockH       = 118;                        # est. rendered height of the clockFont line (no metrics API)
  dateH        = 40;                         # est. rendered height of the dateFont line
  markPx       = 48 * sc;                    # matches greeter NIX_MARK_PX
  markGap      = 14 * sc;                    # mark → clock, matches greeter spacing
  clockDateGap = 140;                        # clock centre → date centre (already centre-anchored)

  clockMid = 50 - 31 * sc;                   # ← live-tune knob; +y raises the cluster
  # centre-to-centre: half the clock line + the gap + half the mark.
  markOff  = clockMid + clockH / 2 + markGap + markPx / 2;
  dateOff  = clockMid - clockDateGap;

  # Scrim: a full-bleed band darkening the mid zone so the mark + clock + date
  # stay legible on busy / same-value wallpapers (the flat pass dropped their
  # text-shadows). HALL is the palette ground-floor fill — FORTE/REST over it is
  # a palette-guaranteed contrast pair, so no per-theme tuning; on a HALL=#000000
  # theme it degrades to a plain 55%-black darkening, still the right read.
  # quantum-clock's lock face is a WORD clock ("twenty-five past eleven"), so no
  # fitted width can frame it — hence full-bleed. Centred on the same midpoint as
  # the cluster (valign=center), so it tracks the text on any display.
  scrimPad  = 32 * sc;
  scrimTop  = markOff + markPx / 2 + scrimPad;      # mark top + pad, above centre
  scrimBot  = 0 - dateOff + dateH / 2 + scrimPad;   # date bottom + pad, below centre
  scrimH    = scrimTop + scrimBot;
  scrimYOff = (scrimTop - scrimBot) / 2;               # straddle the cluster, not the centre
  scrimW    = 6000;                                    # exceeds any output; clips to the screen sides

  # Flat vocabulary (swaync kit): no shadow primitive in hyprlock's config
  # language, so "flat" here is the absence of faked depth. A drmis-tinted nix
  # mark (state/nix-mark-img, flat REST silhouette — same mark the greeter and
  # the logout popup carry) sits above the clock; clock + date are bare labels.
  # The password input is a STAGE pill with a 1px thread-weight outline and
  # radiusMd corners — fill + hairline + radius is the whole read.
in ''
  # hyprlock 0.9.5 dropped general:no_fade_in and general:disable_loading —
  # confirmed live, both logged "does not exist" parse errors on every lock.
  # no_fade_in=false was already the default (no-op); disable_loading has no
  # replacement key, so both are just gone rather than reimplemented.
  general {
      hide_cursor        = true
      fractional_scaling = 1
  }

  background {
      path        = ${home}/.local/state/wallpaper-img
      blur_passes = 0
      brightness  = 1.0
      contrast    = 1.0
  }

  # ── Scrim: full-bleed band, centred on the cluster ─────────────────────
  # Declared before the mark/clock/date so hyprlock (file-order z-stacking)
  # paints them on top. halign=left, not center: on the Surface's fractional-
  # scaled panel, hyprlock v0.9.5 centres an explicitly-sized shape wrong (the
  # scrim rendered hundreds of px left of centre — confirmed live, text
  # widgets were unaffected since they auto-size). Pinning the left edge to
  # x=0 needs no centring arithmetic at all: a 6000px-wide band from x=0
  # still clears the right edge of any monitor at any scale.
  shape {
      size        = ${toString scrimW}, ${toString scrimH}
      color       = rgba(${h p.HALL}8c)
      rounding    = 0
      border_size = 0
      position    = 0, ${toString scrimYOff}
      halign      = left
      valign      = center
  }

  # ── mark + clock + date — one cluster, centred ─────────────────────────

  # nix mark — flat REST silhouette, drmis-managed (state/nix-mark-img).
  # hyprlock can't recolour; the file is already tinted by home/nix-mark.
  image {
      path        = ${home}/.local/state/nix-mark-img
      size        = ${toString markPx}
      rounding    = 0
      border_size = 0
      position    = 0, ${toString markOff}
      halign      = center
      valign      = center
  }

  # Clock
  label {
      text        = cmd[update:1000] quantum-clock lock 2>/dev/null || echo "--"
      color       = rgba(${h p.FORTE}ff)
      font_size   = ${toString clockFont}
      font_family = Josefin Sans
      position    = 0, ${toString clockMid}
      halign      = center
      valign      = center
  }

  # Date
  label {
      text        = cmd[update:60000] date +"%A, %d %B"
      color       = rgba(${h p.REST}ff)
      font_size   = ${toString dateFont}
      font_family = Josefin Sans
      position    = 0, ${toString dateOff}
      halign      = center
      valign      = center
  }

  # ── BOTTOM: password input — flat STAGE pill, 1px thread outline ────────

  input-field {
      size              = ${px 360}, ${px 52}
      outline_thickness = ${px 1}
      dots_size         = 0.28
      dots_spacing      = 0.4
      dots_center       = true

      outer_color       = rgba(${h p.SCORE}8c)
      inner_color       = rgba(${h p.STAGE}ff)
      font_color        = rgba(${h p.SCORE}ff)
      fade_on_empty     = false
      rounding          = ${toString l.radiusMd}
      check_color       = rgba(${h p.PIANO}ff)
      fail_color        = rgba(${h p.FORTE}ff)
      fail_text         = @@SNARK@@
      placeholder_text  =
      hide_input        = false
      position          = 0, ${px 205}
      halign            = center
      valign            = bottom
  }
''
